name: deploy-app

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: "app/Dockerfile"
          push: true
          tags: malkops/netology-app:${{ github.ref_name }}
  deploy-app:
    runs-on: ubuntu-latest
    needs: push-image
    steps:
      - name: Install YC app
        run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yc -n
      - name: Install kubectl and helm
        run: |
          wget https://get.helm.sh/helm-v3.14.1-linux-amd64.tar.gz && tar -xf helm-v3.14.1-linux-amd64.tar.gz -C /opt
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - name: Get kubernetes credentials
        run: |
          /opt/yc/bin/yc config profile create default
          /opt/yc/bin/yc config set token ${{ secrets.YC_TOKEN }}
          /opt/yc/bin/yc config set cloud-id ${{ secrets.CLOUD_ID }}
          /opt/yc/bin/yc config set folder-id ${{ secrets.FOLDER_ID }}
          /opt/yc/bin/yc managed-kubernetes cluster get-credentials diploma-cluster --external
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        run: |
          sed -i 's/appVersion: 0.1.0/appVersion: ${{ github.ref_name }}/' helm/Chart.yaml
          cat /home/runner/.config/yandex-cloud/config.yaml
          helm upgrade -i netologi-diploma helm/
