name: terraform

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
      TF_VAR_service_account_key_file: ${{ secrets.TF_VAR_SERVICE_ACCOUNT_KEY_FILE }}
      TF_VAR_get_creds: ${{ secrets.TF_VAR_GET_CREDS }}
      DIPLOMA: ${{ secrets.TF_KEY_BASE64 }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy .terraformrc.tfrc to home dir
        run: cp terraform/.terraformrc.tfrc ~/
      - name: Save key file
        run: echo $DIPLOMA | base64 --decode > /home/runner/diploma.json
      - name: Download terraform
        run: |
          cd terraform
          wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
          unzip terraform_1.5.7_linux_amd64.zip
          ./terraform -v
          ./terraform init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY" && ./terraform apply --auto-approve
