name: terraform

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
      TF_VAR_service_account_key_file: ${{ secrets.TF_VAR_SERVICE_ACCOUNT_KEY_FILE }}
      TF_VAR_get_creds: ${{ secrets.TF_VAR_GET_CREDS }}
      DIPLOMA: ${{ secrets.TF_KEY_BASE64 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy .terraformrc.tfrc to home dir
        run: cp terraform/.terraformrc.tfrc ~/
      - name: Save key file
        run: echo $DIPLOMA | base64 --decode > /home/runner/diploma.json
      - name: Download terraform
        run: |
          cd terraform
          wget https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_darwin_amd64.zip
          unzip terraform_1.7.3_darwin_amd64.zip
      - name: Terraform apply
        run: terraform apply
      
